<?php

return [
    'temples' => [
        'Sun' => [
            'primary' => ['name' => 'Sooriyanar Kovil', 'location' => 'Aduthurai, Thanjavur', 'lat' => 11.0234, 'lng' => 79.4812],
            'others' => [],
        ],
        'Moon' => [
            'primary' => ['name' => 'Kailasanathar Temple', 'location' => 'Thingaloor, Thanjavur', 'lat' => 11.0567, 'lng' => 79.4123],
            'others' => [],
        ],
        'Mars' => [
            'primary' => ['name' => 'Vaitheeswaran Kovil', 'location' => 'Mayiladuthurai', 'lat' => 11.2322, 'lng' => 79.6576],
            'others' => [],
        ],
        'Mercury' => [
            'primary' => ['name' => 'Thiruvenkadu Temple', 'location' => 'Thiruvenkadu, Mayiladuthurai', 'lat' => 11.2789, 'lng' => 79.7234],
            'others' => [],
        ],
        'Jupiter' => [
            'primary' => ['name' => 'Apatsahayesvarar Temple', 'location' => 'Alangudi, Tiruvarur', 'lat' => 10.7988, 'lng' => 79.4412],
            'others' => [],
        ],
        'Venus' => [
            'primary' => ['name' => 'Agniswarar Temple', 'location' => 'Kanjanur, Thanjavur', 'lat' => 10.9756, 'lng' => 79.3234],
            'others' => [],
        ],
        'Saturn' => [
            'primary' => ['name' => 'Thirunallar Saneeswaran Temple', 'location' => 'Thirunallar, Karaikal', 'lat' => 10.9897, 'lng' => 79.8123],
            'others' => [
                ['name' => 'Shani Shingnapur', 'location' => 'Ahmednagar, Maharashtra', 'lat' => 19.3916, 'lng' => 74.1442],
            ],
        ],
        'Rahu' => [
            'primary' => ['name' => 'Sri Naganathaswamy Temple', 'location' => 'Thirunageswaram, Thanjavur', 'lat' => 10.9612, 'lng' => 79.2789],
            'others' => [
                ['name' => 'Sri Kalahasti Temple', 'location' => 'Tirupati, Andhra Pradesh', 'lat' => 13.7496, 'lng' => 79.6983],
            ],
        ],
        'Ketu' => [
            'primary' => ['name' => 'Naganathaswamy Temple', 'location' => 'Keezhperumpallam, Mayiladuthurai', 'lat' => 11.2456, 'lng' => 79.7567],
            'others' => [
                ['name' => 'Sri Kalahasti Temple', 'location' => 'Tirupati, Andhra Pradesh', 'lat' => 13.7496, 'lng' => 79.6983],
            ],
        ],
    ],

    'remedies' => [
        'Sun' => [
            'day' => 'Sunday',
            'gemstone' => 'Ruby',
            'color' => 'Red',
            'metal' => 'Gold',
            'mantra' => 'Om Suryaya Namaha',
            'mantra_count' => 108,
            'offerings' => ['Red flowers', 'Vermilion', 'Wheat', 'Jaggery'],
            'fasting' => 'Sunday',
            'donations' => ['Wheat', 'Red cloth', 'Copper vessel', 'Jaggery'],
            'deity' => 'Lord Surya',
        ],
        'Moon' => [
            'day' => 'Monday',
            'gemstone' => 'Pearl',
            'color' => 'White',
            'metal' => 'Silver',
            'mantra' => 'Om Shram Shrim Shraum Sah Chandraya Namah',
            'mantra_count' => 108,
            'offerings' => ['White flowers', 'Milk', 'Rice', 'White cloth'],
            'fasting' => 'Monday',
            'donations' => ['Rice', 'Silver', 'White cloth', 'Conch shell'],
            'deity' => 'Lord Shiva',
        ],
        'Mars' => [
            'day' => 'Tuesday',
            'gemstone' => 'Red Coral',
            'color' => 'Red',
            'metal' => 'Copper',
            'mantra' => 'Om Mangalaya Namaha',
            'mantra_count' => 108,
            'offerings' => ['Red flowers', 'Red lentils', 'Jaggery', 'Red cloth'],
            'fasting' => 'Tuesday',
            'donations' => ['Red lentils (Masoor dal)', 'Red cloth', 'Copper utensils'],
            'deity' => 'Lord Hanuman / Lord Kartikeya',
        ],
        'Mercury' => [
            'day' => 'Wednesday',
            'gemstone' => 'Emerald',
            'color' => 'Green',
            'metal' => 'Bronze',
            'mantra' => 'Om Budhaya Namah',
            'mantra_count' => 108,
            'offerings' => ['Green lentils (Moong dal)', 'Green vegetables', 'Green cloth'],
            'fasting' => 'Wednesday',
            'donations' => ['Green lentils', 'Green cloth', 'Green vegetables'],
            'deity' => 'Lord Vishnu',
        ],
        'Jupiter' => [
            'day' => 'Thursday',
            'gemstone' => 'Yellow Sapphire',
            'color' => 'Yellow',
            'metal' => 'Gold',
            'mantra' => 'Om Graam Greem Graum Sah Gurave Namah',
            'mantra_count' => 108,
            'offerings' => ['Yellow flowers', 'Bananas', 'Turmeric', 'Yellow sweets', 'Ghee lamp'],
            'fasting' => 'Thursday',
            'donations' => ['Yellow cloth', 'Turmeric', 'Bananas', 'Bengal gram (Chana dal)'],
            'deity' => 'Lord Dakshinamurthy / Lord Vishnu',
        ],
        'Venus' => [
            'day' => 'Friday',
            'gemstone' => 'Diamond',
            'color' => 'White',
            'metal' => 'Silver',
            'mantra' => 'Om Draam Dreem Draum Sah Shukraya Namah',
            'mantra_count' => 108,
            'offerings' => ['White flowers', 'White sweets', 'White rice', 'White cloth'],
            'fasting' => 'Friday',
            'donations' => ['White cloth', 'White rice', 'Silk', 'Perfume'],
            'deity' => 'Goddess Lakshmi',
        ],
        'Saturn' => [
            'day' => 'Saturday',
            'gemstone' => 'Blue Sapphire',
            'color' => 'Blue/Black',
            'metal' => 'Iron',
            'mantra' => 'Om Sham Shanicharaya Namah',
            'mantra_count' => 108,
            'offerings' => ['Black sesame seeds', 'Mustard oil', 'Blue flowers', 'Black cloth'],
            'fasting' => 'Saturday',
            'donations' => ['Black sesame seeds', 'Mustard oil', 'Iron utensils', 'Black gram (Urad dal)'],
            'deity' => 'Lord Shani Dev / Lord Hanuman',
        ],
        'Rahu' => [
            'day' => 'Saturday',
            'gemstone' => 'Hessonite (Gomed)',
            'color' => 'Brown',
            'metal' => 'Silver',
            'mantra' => 'Om Bhraam Bhreem Bhroum Sah Rahave Namaha',
            'mantra_count' => 108,
            'offerings' => ['Barley', 'Mustard seeds', 'Blue cloth', 'Coconut'],
            'fasting' => 'Saturday',
            'donations' => ['Barley', 'Mustard seeds', 'Coins', 'Blue cloth'],
            'deity' => 'Lord Ganesha / Goddess Durga',
        ],
        'Ketu' => [
            'day' => 'Tuesday',
            'gemstone' => "Cat's Eye (Lahsuniya)",
            'color' => 'Grey',
            'metal' => 'Silver',
            'mantra' => 'Om Sraam Sreem Sraum Sah Ketave Namah',
            'mantra_count' => 108,
            'offerings' => ['Barley', 'Sesame seeds', 'Grey cloth'],
            'fasting' => 'Tuesday',
            'donations' => ['Sesame seeds', 'Blankets', 'Seven grains mix'],
            'deity' => 'Lord Ganesha / Lord Shiva',
        ],
    ],

    'effect_levels' => [
        'benefic_houses' => [1, 2, 5, 9, 11],
        'malefic_houses' => [6, 8, 12],
        'mixed_houses' => [3, 4, 7, 10],
    ],
];
